
; COURSE: ELEN2006
; STUDENT NAME : 
; DATE: 04-JUNE-2020
; DISCRIPTION : THERMISTOR 
;MCP9700 series
; 
.INCLUDE "./m328Pdef.inc"
	.ORG 0x0000 JMP START  
	.ORG 0x0012 JMP READ_DATA
START:
		LDI R16 ,HIGH (RAMEND)   ; INITALISE START POINTER
		OUT SPH ,R16
		LDI R16 ,LOW (RAMEND)   
		OUT SPL ,R16

		SEI
		LDI R16,0xFF			;ADC CONFIGURATION VARIABLES
		OUT DDRD, R16 
		LDI R16,0 
		OUT DDRC, R16 
		LDI R16,0x87
		STS ADCSRA, R16
		LDI R16, 0xE0
		STS ADMUX , R16
		LDI  R16, 0xC7
		STS ADCSRA , R16
READ_ADC :
	RJMP READ_ADC
	RCALL DISPLAY
READ_DATA :
		RCALL DISPLAY
		LDI R16 , 0B01010000
		STS ADCSRA   , R16
		LDS R16 , ADCH
		LDI  R16, 0xC7
		STS ADCSRA , R16
		CPI R16 , 50						; 50 IS NUMBER THE REPRESENT 50mV IT IS 0TH DEGREE.
		BRLT NEGATIVE_READING				; BRANCH TO COMPUTE NEGATIVE READING  	  
		BRGE POSITIVE_READING				; COMPUTE POSITIVE READING
		RETI


POSITIVE_READING:
	CLR R17			; CLEAR THE THREE REGISTER FOR THE THREE SEVEN SEGMENT
	CLR R18

	CBI PORTD ,6
	CBI PORTD , 7
	LDI R28 , 50
	SUB R16,R28
	LOOP_COUNTER:
		CPI R16 , 0
		RJMP READ_ADC
		DEC R16
		LOOP_COUNTER_1 :
			 CPI R20 , 9
			 BREQ LOOP_COUNTER_2
			 INC R20
			 RJMP LOOP_COUNTER
		LOOP_COUNTER_2:
			 CPI R19 , 9
			 BREQ LED_ON
			 INC R19
			 CLR R20
			 RJMP LOOP_COUNTER
		LED_ON:
		SBI DDRD , 6
		SBI PORTD , 6				; TURN RED LED ON IF TEMPERATURE RISES BEYOND 99
		RJMP READ_ADC


NEGATIVE_READING:
	MOV R17 , R16					;R16 TO R17 SO THAT WE DO INVETION 
	LDI R16, 50						; IDEALLY AT THIS POINT WE WOULD HAVE NEGATIVE READING
	SUB R16 , R17					; WE SUBSTRACT TO GET POSITIVE READING
	CALL POSITIVE_READING
LED_ON_2 :
	SBI DDRD ,7
	SBI PORTD , 7					; TURN GREEN LED ON IF THE TEMPERATURE FALL BELLOW ZER0        
	RJMP READ_ADC
	
DISPLAY:							;	
	OUT PORTD, R18			; TURN ON FIRST SEVEN SEGMENT DISPLAY
	SBI PORTD , 4			
	CBI PORTD , 5
	CALL DELAY
	OUT PORTD, R19			; TURN ON SECOND SEVEN SEGMENT DISPLAY
	SBI PORTD , 5
	CBI PORTD , 4
	CALL DELAY
	RET

DELAY:						;DELAY LOOP BETWEEN BETWEEN SWITCHING  THE TRANSISTORS
    ldi  r18, 2
    ldi  r19, 56
    ldi  r20, 174
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1











